apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.api.name }}-clusterrolebinding
subjects:
- kind: ServiceAccount
  name: {{ .Values.api.name }}-serviceaccount
  namespace: default
roleRef:
  kind: ClusterRole
  name: {{ .Values.api.name }}-full-access-role
  apiGroup: rbac.authorization.k8s.io
