apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.api.name }}-nodeport-service
spec:
  selector:
    app: {{ .Values.api.name }}-app
  ports:
    - protocol: TCP
      port: {{ .Values.api.internal_port }}     
      nodePort: {{ .Values.api.exposed_port }}    
  type: NodePort         
