kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ printf "minecraft-data-pvc-%s" .Values.minecraft.motd }}
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.volume.storage }}
